#!/usr/bin/python3
#could use psutil, but stick with builtins for now...
import subprocess
import sys
terminate_found = True

def match_procs(terminate_found):
    found_procs = []
    procs = subprocess.check_output(['ps','-e']).decode()
    for l in procs.split("\n"):
        if "gphoto" in l and "-" in l:
            pid = l.strip().split(" ",1)[0]
            proc = l.strip().rsplit(" ",1)[-1]
            print("interfering process? ",pid,proc)
            found_procs.append((pid,proc))
            if terminate_found:
                print("attempting to kill pid",pid)
                subprocess.call(['kill','-9',pid])
                #match_procs()
    return found_procs

found_procs = match_procs(terminate_found)
if found_procs:
    sys.exit(1)
else:
    #passing
    sys.exit(0)